title: Andrew Barry - IT and Cybersecurity blog
description: A blog about IT, Cybersecurity, and Programming by Andrew Barry. Guided tutorials and documentation of learning advanced concepts in I.T fields.
author: Andrew Barry
email: andrewbarry025@outlook.com
url: https://AndrewBarry-sec.github.io
language: en


# Build settings
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0



# plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme


# navigation
header_pages:
  - index.md
  - about.md
  - tutorials.md
  - learning-journey.md