title: Andrew Barry - IT and Cybersecurity blog
description: A blog about IT, Cybersecurity, and Programming by Andrew Barry. Guided tutorials and documentation of learning advanced concepts in I.T fields.
author: Andrew Barry
email: andrewbarry025@outlook.com
url: https://AndrewBarry-sec.github.io
language: en


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Theme settings
minimal_mistakes_skin: dark

# Author info
author:
  name: "Andrew Barry"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AndrewBarry-sec"


# plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /page:num/